---
- hosts: all
  become: yes
  tasks:
   - name: install httpd server
     yum:
      name: httpd
      state: present
   - name: start httpd server
     service: 
      name: httpd
      state: started