---
- hosts: all
  become: yes
  vars:
   HubandName: Imran Shaik
   WifeName: Afrin Shaik
  tasks:
   - name: install httpd server
     yum:
      name: httpd
      state: present
   - name: start httpd server
     service: 
      name: httpd
      state: started